databases:
  - name: parent-monitor-db
    databaseName: parent_monitor
    user: parent_monitor
    plan: basic-256mb

services:
  - type: web
    name: parent-monitor
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: BIND_CODE
        value: 918918
      - key: DATABASE_URL
        fromDatabase:
          name: parent-monitor-db
          property: connectionString
